// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpM-aJvdDyD8c8WhlrKnoyw7bRx2yU4P8',
    appId: '1:278343999737:web:a6bce171122c2c3cf40228',
    messagingSenderId: '278343999737',
    projectId: 'aktivite-dfaf0',
    authDomain: 'aktivite-dfaf0.firebaseapp.com',
    storageBucket: 'aktivite-dfaf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVEOYV5FbqLYpmEu9STjano3Wh6EqLzk',
    appId: '1:278343999737:android:e3bfe4570def2ed6f40228',
    messagingSenderId: '278343999737',
    projectId: 'aktivite-dfaf0',
    storageBucket: 'aktivite-dfaf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBGwvh2mUb6ek-FM-5fEpy91R7u9PGveo',
    appId: '1:278343999737:ios:c7829e1df5070625f40228',
    messagingSenderId: '278343999737',
    projectId: 'aktivite-dfaf0',
    storageBucket: 'aktivite-dfaf0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBGwvh2mUb6ek-FM-5fEpy91R7u9PGveo',
    appId: '1:278343999737:ios:9d8cf10fd6e4b92ff40228',
    messagingSenderId: '278343999737',
    projectId: 'aktivite-dfaf0',
    storageBucket: 'aktivite-dfaf0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
